### ISSUE TITLE
How to disconnect controller?

### ISSUE THREAD

**Issue by tapererwaj** [ricardoquesada/bluepad32#36] opened 2023-05-20 03:57 UTC
Is there a built-in method in this library that I can use to disconnect a connected controller after pressing any button on the controller , if not, can you suggest a way to achieve this.

**Comment by ricardoquesada** [comment] 2023-05-20 12:42
fixed, I'm assuming you are using the Arduino API.

will be part of the next stable release


https://gitlab.com/ricardoquesada/bluepad32/-/commit/227db920471c5fe78f40820e090124748df2cbcc
https://gitlab.com/ricardoquesada/bluepad32/-/commit/a702cc6c4b210c3df32f5ff86fcc5ce8b98c0a37

**Closed by ricardoquesada** 2023-05-20 12:42 UTC

**Comment by tapererwaj** [comment] 2023-05-20 15:02
Hello, thank you for your reply.

When will the next stable release be available?

**Comment by ricardoquesada** [comment] 2023-05-20 15:06
I don't have a date, but soon :)

perhaps in one week or less

**Comment by tapererwaj** [comment] 2023-05-20 15:07
Okay, much appreciated

**Comment by ricardoquesada** [comment] 2023-05-21 03:18
v3.7.2 released

**Comment by tapererwaj** [comment] 2023-05-21 04:01
> fixed, I'm assuming you are using the Arduino API.
> 
> will be part of the next stable release
> 
> https://gitlab.com/ricardoquesada/bluepad32/-/commit/227db920471c5fe78f40820e090124748df2cbcc https://gitlab.com/ricardoquesada/bluepad32/-/commit/a702cc6c4b210c3df32f5ff86fcc5ce8b98c0a37

Can I also use this for the ESP32 DEVKIT?

**Comment by ricardoquesada** [comment] 2023-05-21 04:13
yep. if it works with regular ESP32 Arduino, then it should work with ESP32-Bluepad32 Ardunio.

**Comment by tapererwaj** [comment] 2023-05-21 07:29
I have tried using the disconnect class method through the Controller example as shown in the image below:

<img width="469" alt="image" src="https://github.com/ricardoquesada/bluepad32/assets/94379011/f4a1eaf1-339e-4380-a27a-76dc5e2b949f">

But the ESP32 just reboots and gives me the following error:
<img width="685" alt="image" src="https://github.com/ricardoquesada/bluepad32/assets/94379011/2cf1dd53-78b3-464e-853d-046f246bfdbb">

How can I resolve this issue?

**Comment by ricardoquesada** [comment] 2023-05-21 13:51
mmm.... let me double check it.

**Comment by ricardoquesada** [comment] 2023-05-21 14:28
I cannot reproduce it... seems to be working ok with me.

Please provide:

- Platform you are using:  Arduino IDE (which version), Arduino ESP-IDF (which ESP 4.4 version), etc..
- OS: Linux, Windows, etc... (which version)
- Gamepad and the FW used by the gamepad
- somewhere post your  entire sketch (not a screenshot... the code so that I can copy paste it)
- the more info you add, the easier for me

**Comment by tapererwaj** [comment] 2023-05-22 12:58
Platform: Arduino IDE v2.1.0
ESP32 Chip - ESP32-D0WDQ6 (revision v1.0)
esptool.py v4.5.1
OS - Windows 11
Controller - PS5 Dual Sense

Arduino IDE Sketch:
[Controller.zip](https://github.com/ricardoquesada/bluepad32/files/11531236/Controller.zip)

**Comment by tapererwaj** [comment] 2023-05-22 12:58
Platform: Arduino IDE v2.1.0
ESP32 Chip - ESP32-D0WDQ6 (revision v1.0)
esptool.py v4.5.1
OS - Windows 11
Controller - PS5 Dual Sense

Arduino IDE Sketch:
[Controller.zip](https://github.com/ricardoquesada/bluepad32/files/11531236/Controller.zip)

**Comment by ricardoquesada** [comment] 2023-05-23 01:29
In you code you have:

```
      if (myGamepad->x()) {
        // try to disconnect the controller
        myGamepad->disconnect();
        return;  // <--- DO NOT RETURN FROM update();
      }
```

just remove the `return;`

**Comment by tapererwaj** [comment] 2023-05-23 12:01
It works, thank you

**Comment by ricardoquesada** [comment] 2023-05-23 13:26
look at the NINA code, which is similar as what you want but using SPI:
https://gitlab.com/ricardoquesada/bluepad32/-/blob/main/docs/plat_nina.md
